1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np
m = np.arange(12).reshape((3,4))
num = 0
den = 0
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        num += m[i,j]
        den += 1
mean = num/den
print("Total mean = ", mean)

Total mean =  5.5


In [3]:
for i in range(m.shape[0]):
    num = 0
    den = 0
    for j in range(m.shape[1]):
        num += m[i,j]
        den +=1
    mean = num/den
    print("Row", i, ", mean =", mean)

Row 0 , mean = 1.5
Row 1 , mean = 5.5
Row 2 , mean = 9.5


In [4]:
for i in range(m.shape[1]):
    col = m[:,i]
    num = 0
    den = 0
    for j in col:
        num += j
        den += 1
    mean = num/ den
    print("Column", i, ", mean = ", mean)

Column 0 , mean =  4.0
Column 1 , mean =  5.0
Column 2 , mean =  6.0
Column 3 , mean =  7.0


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [5]:
import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print(u)
print(v)

[1 3 5 7]
[2 4 6 8]


In [6]:
print(np.outer(u,v))

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [7]:
for i in u:
    row = []
    for j in v:
        row.append(i*j)
    print(row)

[2, 4, 6, 8]
[6, 12, 18, 24]
[10, 20, 30, 40]
[14, 28, 42, 56]


In [8]:
u_broad = np.tile(u, (4,1)).T
v_broad = np.tile(v, (4,1))

print(u_broad,'\n')
print(v_broad,'\n')

print(u_broad*v_broad)

[[1 1 1 1]
 [3 3 3 3]
 [5 5 5 5]
 [7 7 7 7]] 

[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [9]:
import numpy as np
a = np.tile(np.arange(0,6,1), (10, 1)).T
b = np.arange(0,1,0.1)
c = a+b
print(c)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]


In [12]:
for i in range(c.shape[0]):
    for j in range(0,5):
        c[i,j] = 0
print(c)

[[0.  0.  0.  0.  0.  0.5 0.6 0.7 0.8 0.9]
 [0.  0.  0.  0.  0.  1.5 1.6 1.7 1.8 1.9]
 [0.  0.  0.  0.  0.  2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  0.  3.5 3.6 3.7 3.8 3.9]
 [0.  0.  0.  0.  0.  4.5 4.6 4.7 4.8 4.9]
 [0.  0.  0.  0.  0.  5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [13]:
import math as m
import numpy as np
a = np.linspace(0, (2*np.pi), 100)
a




array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 3.87145761,
       3.93492413, 3.99839065, 4.06185717, 4.12532369, 4.1887902 ,
       4.25225672, 4.31572324, 4.37918976, 4.44265628, 4.5061228 ,
       4.56958931, 4.63305583, 4.69652235, 4.75998887, 4.82345539,
       4.88692191, 4.95038842, 5.01385494, 5.07732146, 5.14078798,
       5.2042545 , 5.26772102, 5.33118753, 5.39465405, 5.45812057,
       5.52158709, 5.58505361, 5.64852012, 5.71198664, 5.77545316,
       5.83891968, 5.9023862 , 5.96585272, 6.02931923, 6.09278575,
       6.15625227, 6.21971879, 6.28318531])

In [14]:
b = a[::10]
b

array([0.        , 0.63466518, 1.26933037, 1.90399555, 2.53866073,
       3.17332591, 3.8079911 , 4.44265628, 5.07732146, 5.71198664])

In [15]:
c = a[::-1]
c

array([6.28318531, 6.21971879, 6.15625227, 6.09278575, 6.02931923,
       5.96585272, 5.9023862 , 5.83891968, 5.77545316, 5.71198664,
       5.64852012, 5.58505361, 5.52158709, 5.45812057, 5.39465405,
       5.33118753, 5.26772102, 5.2042545 , 5.14078798, 5.07732146,
       5.01385494, 4.95038842, 4.88692191, 4.82345539, 4.75998887,
       4.69652235, 4.63305583, 4.56958931, 4.5061228 , 4.44265628,
       4.37918976, 4.31572324, 4.25225672, 4.1887902 , 4.12532369,
       4.06185717, 3.99839065, 3.93492413, 3.87145761, 3.8079911 ,
       3.74452458, 3.68105806, 3.61759154, 3.55412502, 3.4906585 ,
       3.42719199, 3.36372547, 3.30025895, 3.23679243, 3.17332591,
       3.10985939, 3.04639288, 2.98292636, 2.91945984, 2.85599332,
       2.7925268 , 2.72906028, 2.66559377, 2.60212725, 2.53866073,
       2.47519421, 2.41172769, 2.34826118, 2.28479466, 2.22132814,
       2.15786162, 2.0943951 , 2.03092858, 1.96746207, 1.90399555,
       1.84052903, 1.77706251, 1.71359599, 1.65012947, 1.58666

In [16]:
mask = (abs(np.sin(a) - np.cos(a) < 0.1))
a[mask] 

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 3.87145761,
       3.93492413, 3.99839065, 4.06185717, 4.12532369, 4.1887902 ,
       4.25225672, 4.31572324, 4.37918976, 4.44265628, 4.5061228 ,
       4.56958931, 4.63305583, 4.69652235, 4.75998887, 4.82345539,
       4.88692191, 4.95038842, 5.01385494, 5.07732146, 5.14078798,
       5.2042545 , 5.26772102, 5.33118753, 5.39465405, 5.45812057,
       5.52158709, 5.58505361, 5.64852012, 5.71198664, 5.77545316,
       5.83891968, 5.9023862 , 5.96585272, 6.02931923, 6.09278575,
       6.15625227, 6.21971879, 6.28318531])

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [17]:
import numpy as np
v = np.arange(1,11)
u = np.tile(v, (10,1)).T
m = u*v
m

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [18]:
d = np.diag(m)
s = 0
for i in d:
    s += i
print("Trace of the matrix is:", s)

Trace of the matrix is: 385


In [19]:
anti_matrix = np.fliplr(m)
anti_matrix

array([[ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1],
       [ 20,  18,  16,  14,  12,  10,   8,   6,   4,   2],
       [ 30,  27,  24,  21,  18,  15,  12,   9,   6,   3],
       [ 40,  36,  32,  28,  24,  20,  16,  12,   8,   4],
       [ 50,  45,  40,  35,  30,  25,  20,  15,  10,   5],
       [ 60,  54,  48,  42,  36,  30,  24,  18,  12,   6],
       [ 70,  63,  56,  49,  42,  35,  28,  21,  14,   7],
       [ 80,  72,  64,  56,  48,  40,  32,  24,  16,   8],
       [ 90,  81,  72,  63,  54,  45,  36,  27,  18,   9],
       [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]])

In [20]:
anti_diag = np.diag(anti_matrix)
print("Anti-diagonal is:", anti_diag)

Anti-diagonal is: [10 18 24 28 30 30 28 24 18 10]


In [21]:
offset_d = []
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if(j == i+1):
            offset_d.append(m[i,j])
print("diagonal offset by 1 is:", offset_d) 

diagonal offset by 1 is: [2, 6, 12, 20, 30, 42, 56, 72, 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)